# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.security.login_form_authenticator:
       class: AppBundle\Security\LoginFormAuthenticator
       arguments: ["@form.factory","@doctrine.orm.default_entity_manager","@Router","@security.password_encoder"]
    app.doctrine.hash_password_listener:
        class : AppBundle\Doctrine\HashPasswordListener
        arguments : ["@security.password_encoder"]
        tags:
           - { name: doctrine.event_subscriber }
    app.last_login_subscriber:
            class: AppBundle\EventListener\LastLoginSubscriber
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: kernel.event_subscriber }
    app.facebook_authenticator:
                class: AppBundle\Security\FacebookAuthenticator
                arguments: ["@knpu.oauth2.client.my_facebook_client","@doctrine.orm.default_entity_manager","@Router"]
    app.api_token_authenticator:
            class: AppBundle\Security\ApiTokenAuthenticator
            arguments: ["@doctrine.orm.entity_manager"]

    oauth.twitter:
            class: League\OAuth1\Client\Server\Twitter
            arguments:
                    -
                                    identifier: %twitter_identifier%
                                    secret: %twitter_secret%
                                    callback_uri: %twitter_callback_uri%
    app.logout.listener:
            class: AppBundle\Listener\LogoutListener
            arguments: ["@doctrine.orm.entity_manager"]





#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
